### ISSUE TITLE
Create dist version

### ISSUE THREAD

**Issue by migo315** [migo315/coaster.js#1]
Currently we only have a `src` file. We should provide a `dist` file for easy use. The dist file should be compiled (babel) and minified.

**Comment by DAMMAK** [comment]
okay!.. cool... it interest me.. can you assign it to me

**Comment by migo315** [comment]
done ;-)

**Comment by DAMMAK** [comment]
okay !! cool

**Comment by migo315** [comment]
I have merged it. Thanks a lot ;-)

**Comment by DAMMAK** [comment]
okay! you welcome
