### ISSUE TITLE
Add missing test

### ISSUE THREAD

**Issue by migo315** [migo315/coaster.js#10]
There is one little part in the query builder which is untested. This should be tested too.
See https://coveralls.io/builds/26267947/source?filename=src/build-query.js

**Comment by JacobMGEvans** [comment]
I would like to be assigned for this one and to try and tackle it.

**Comment by amnuts** [comment]
ahh.. I had just written the test and was about to ask the same :)

**Comment by JacobMGEvans** [comment]
If you already did it then I say you beat me to the punch 😄 
Great work!
