### ISSUE TITLE
Basic tests

### ISSUE THREAD

**Issue by migo315** [migo315/coaster.js#2]
We should write some very basic integration tests. Maybe with https://jestjs.io/docs/en/getting-started.html ?

**Comment by Jc7j** [comment]
I can try this!

**Comment by migo315** [comment]
I've added a first, very simple test with jest:
https://github.com/migo315/coaster.js/blob/master/tests/client.test.js

Feedback welcome. I normally do not develop with Javascript.
The tests will automatically run with Github Actions:
https://github.com/migo315/coaster.js/actions

**Comment by Jc7j** [comment]
I'm more familiar with React + Jest but I'll see if I can add more to your test case!

**Comment by migo315** [comment]
All tests are written and merged. I close the issue.
